// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFd-BYTgCkG5utD0tyGc63YIx7TDLPiOM',
    appId: '1:295507185595:web:d26cc4fef0583dff133e9e',
    messagingSenderId: '295507185595',
    projectId: 'sintetico-lima',
    authDomain: 'sintetico-lima.firebaseapp.com',
    storageBucket: 'sintetico-lima.firebasestorage.app',
    measurementId: 'G-8BF5RC8KKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9qvXDp3-vQzCLlEpaZ-es4WII_kIV_nI',
    appId: '1:295507185595:android:faf3270be4d0b489133e9e',
    messagingSenderId: '295507185595',
    projectId: 'sintetico-lima',
    storageBucket: 'sintetico-lima.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt0pUt0GvsbijQ61jgEjxPxCyb8Ip88G8',
    appId: '1:295507185595:ios:32f2878e2fdd724d133e9e',
    messagingSenderId: '295507185595',
    projectId: 'sintetico-lima',
    storageBucket: 'sintetico-lima.firebasestorage.app',
    iosBundleId: 'com.example.sinteticolima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt0pUt0GvsbijQ61jgEjxPxCyb8Ip88G8',
    appId: '1:295507185595:ios:32f2878e2fdd724d133e9e',
    messagingSenderId: '295507185595',
    projectId: 'sintetico-lima',
    storageBucket: 'sintetico-lima.firebasestorage.app',
    iosBundleId: 'com.example.sinteticolima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFd-BYTgCkG5utD0tyGc63YIx7TDLPiOM',
    appId: '1:295507185595:web:77f91b55e4359946133e9e',
    messagingSenderId: '295507185595',
    projectId: 'sintetico-lima',
    authDomain: 'sintetico-lima.firebaseapp.com',
    storageBucket: 'sintetico-lima.firebasestorage.app',
    measurementId: 'G-QX19RBQ0K0',
  );
}
